version: "3.7"
services:
    postgres:
        image: 'postgres:12-alpine'
        environment:
            POSTGRES_USER: root
            POSTGRES_PASSWORD: q1w2e3r4
        ports:
            - '5432:5432'

    cockroach:
        image: 'cockroachdb/cockroach:v19.1.2'
        ports:
            - '26257:26257'
        command: 'start --insecure'

    mongo:
        image: 'mongo:4-xenial'
        environment:
            MONGODB_USER: root
            MONGODB_PASS: q1w2e3r4
        ports:
            - '27017:27017'

    cassandra:
        image: 'cassandra:3'
        ports:
            - '9042:9042'

    scylla:
        image: 'scylladb/scylla:3.0.7'
        ports:
            - '9052:9042'

    redis:
        image: 'redis:5-alpine'
        ports:
            - '6379:6379'

    clickhouse:
        image: 'yandex/clickhouse-server:19'
        ports:
            - '8123:8123'
