---
- name: Setup VM
  hosts: all[0]
  gather_facts: false
  vars:
      - cockroachdb_version: '2.1.3'

  tasks:
      - name: check
        command: 'pgrep cockroach2'
        register: pgrep
        ignore_errors: yes

      - name: Pro
        debug:
            var: pgrep
